### ISSUE TITLE
Checking file download integrity

### ISSUE THREAD

**Issue by AliGouta** [ftpgrab/ftpgrab#12]
Thank you for your post, I think this may bring an answer to my question: I am trying to implement this routine:

1-Copy files from FTP server to my local machine.
2-Check if the downloaded files are fine (i.e. md5checksum).
3-If the download was fine then delete the downloaded files from the FTP server.

And I shoud have an independant file that contains the association between the file located at the FTP server and its MD5. Then I should be able to compare locally if the downloaded file is fine or was corrupted.

-Does your script adress this senario ?
-On which field are you running the MD5 checksum ?
-I need to remove the file that was downloaded from the FTP server while having it locally. Does your script allows me to do that ?

Thank you so much.

**Comment by crazy-max** [comment]
First of all thanks for your interest!

> Does your script adress this senario ?

No my script does not make a full md5sum. Why ? Because make an *md5sum is the same as download the file*.

What i can implement for your purpose :
- You can for example generate a md5sum for your file on your ftp server and ican check a .md5 file available for the remote file on the server.
- Or i can add an implementation to connect to the server via SSH and generate the md5sum via ftp-sync.

**Comment by crazy-max** [comment]
@AliGouta any feedback about my purposes ?
