### ISSUE TITLE
Rewrite from scratch with Go

### ISSUE THREAD

**Issue by crazy-max** [ftpgrab/ftpgrab#36]
- [x] Multiplatform : MacOS, FreeBSD, Linux, Windows, ARM, Android, Synology, QNAP
- [x] Modern CLI interactions with [cobra](https://github.com/spf13/cobra)
- [x] JSON Configuration file
- [x] Detect and merge configuration
- [x] Add [Goreleaser](https://goreleaser.com/)
- [x] [Bolt](https://github.com/boltdb/bolt) db to store hash
- [x] Native FTP client
- [x] Logging with [zerolog](https://github.com/rs/zerolog)
- [x] Send log through email
- [x] Generate responsive emails through [hermes](https://github.com/matcornic/hermes/)
- [x] Review Docker image
- [x] [Embedded cron](https://github.com/crazy-max/cron) using go routines
- [x] Manage base dir
- [x] Set original modtime
- [x] Include/exclude based on regexp
- [x] Ignore files by date (#39)
- [x] Handle mutex
- [ ] Remove local files that no longer exist on the source server (#9)
- [ ] WebUI to customize config (maybe on a further release)

**Comment by masgo** [comment]
I am worried that a rewrite might make this rather small tool which does it's job to something big which is no longer handy for automated purposes. Having something like a webui is nice for beginners, but I would not want it on a server where I call ftpgrab from cron.

So, the question is: what is your goal?

The pro and cons right now are (from my point of view)

- pro: minimal requirements
- pro: quite lightweight and simple
- pro: good for automation with cron, etc.
- pro/con: relies on wget and curl. This is a (big) pro because it makes it flexible and compatible to a lot(!) of servers, crypto alogs, etc. Also, security wise, wget and curl have a larger community which patches security problems.
- con: relies on wget and curl -> the speed is quite low, especially with curl
- con: low portability
- con: the documentation on how to run it as non-root is poor

**Comment by crazy-max** [comment]
Hello @masgo, don't worry, the webui functionality would be available as a "plugin". FTPGrab will remain primarily an automation process.

As far as the complete rewriting is concerned, I chose Golang because I master this language. This will make it easier for me to maintain the code and have cross-compatibility with the different platforms, which is not possible with shell language.

For your concern about the compatibility and support provided by curl or wget, I could use libcurl (binding to golang) but instead I'll use the native FTP protocol in C via Go which on the one hand will greatly improve performance but also improve security.

The fact of choosing curl or wget in the beginning was simply motivated for its portability. With the new version we will be able to keep this portability, lighten the code, extend the functionality and improve performance.
