### ISSUE TITLE
Cannot read directory error if filename contains ; char

### ISSUE THREAD

**Issue by crazy-max** [ftpgrab/ftpgrab#55]
If a file in a directory (FTP  server) contains a `;` the following error occurred :

```
Thu, 18 Jul 2019 19:32:18 UTC ERR Cannot read directory /test/ error="failed parsing MLST entry: type=file;size=7903718;modify=20190718185113;UNIX.mode=0644;UNIX.uid=1001;UNIX.gid=1001;unique=903g5b00215; file;test.txt" source=/test/
```

Bug related to [secsy/goftp](https://github.com/secsy/goftp) module.

**Comment by crazy-max** [comment]
I have made a [fork](https://github.com/crazy-max/goftp) of [secsy/goftp](https://github.com/secsy/goftp) used by FTPGrab to fix some issues like this one and bring improvements :

* Do not fail on incomplete MLSD / LIST entries
* Fix MLST parser
* Check if MLST supported otherwise fallback to LIST
* Add CLNT and UTF8 feature support

**Comment by muirmanders** [comment]
Yes, definitely interested in improvements. Some of your changes overlap with an old PR https://github.com/secsy/goftp/pull/19. 

> Check if MLST supported otherwise fallback to LIST
goftp tries MLST without checking the feature because there are some servers that don't advertise the feature properly. I prefer the linked PR's approach of just "remembering" MLST doesn't work.

**Comment by crazy-max** [comment]
> Some of your changes overlap with an old PR secsy/goftp#19.

@muirmanders Yes indeed but this PR has to many features. I think I will create one PR per feature/fix.
